version: '3.8'

services:
  ifridge:
    build: .
    container_name: ifridge_app
    restart: always
    ports:
      - "8089:8089"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1